d /run/private-vm 0750 root private-vm -
d /var/lib/private-vm 0700 root root -
d /var/lib/private-vm/images 0755 root root -
d /var/lib/private-vm/scratch 0700 root root -
d /var/lib/private-vm/enrollments 0700 root root -
